project:
  name: theflash
  owner: quickstart-eng@amazon.com
  s3_object_acl: public-read
  regions:
    - us-west-2

tests:
  jfrog-artifactory-ami:
    parameters:
      KeyPairName: "$[taskcat_getkeypair]"
      ArtifactoryVersion: 7.0.0
      ArtifactoryRepoUrl: https://earlyaccess.jfrog.io/artifactory/enterprise-rpms 
      RemoteAccessCIDR: "10.0.0.0/16"
      VPCID: vpc-00b12a882dfe6816d
      PublicSubnet1ID: subnet-09a5bfb9f8f0e955e
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3KeyPrefix: "theflash/"
    template: templates/jfrog-ami-creation.template.yaml
    regions:
      - us-east-1      
#  jfrog-artifactory-ec2:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      RemoteAccessCIDR: "10.0.0.0/16"
#      AccessCIDR: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_2]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QSS3BucketName: "$[taskcat_autobucket]"
#      QSS3KeyPrefix: "theflash/"
#      DatabaseInstance: "db.m5.large"
#      ArtifactoryVersion: "6.17.0"
#      NumberOfSecondary: "2"
#      KeystorePassword: "$[taskcat_genpass_8A]"
#      AnsibleVaultPass: "$[taskcat_genpass_8A]"
#      ArtifactoryServerName: "artifactory"
#      CertificateDomain: "localdomain"
#      MasterKey: "override"
#      Certificate: "override"
#      CertificateKey: "override"
#      SMLicensesName: "override"
#    template: templates/jfrog-artifactory-ec2-master.template.yaml
#    regions:
#      - us-east-1
#  jfrog-artifactory-ecs:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      RemoteAccessCIDR: "10.0.0.0/16"
#      AccessCIDR: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_2]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QSS3BucketName: "$[taskcat_autobucket]"
#      QSS3KeyPrefix: "quickstart-jfrog-artifactory/"
#      DatabaseInstance: "db.m5.large"
#      ArtifactoryVersion: "6.11.1"
#      NumberOfSecondary: "2"
#      AnsibleVaultPass: "$[taskcat_genpass_8A]"
#      ArtifactoryServerName: "artifactory"
#      CertificateDomain: "localdomain"
#      MasterKey: "override"
#      Certificate: "override"
#      CertificateKey: "override"
#      SMLicensesName: "override"
#    template: templates/jfrog-artifactory-ecs-master.template.yaml
#    regions:
#      - us-east-2
#  jfrog-artifactory-eks:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      RemoteAccessCIDR: "10.0.0.0/16"
#      AccessCIDR: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_3]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QSS3BucketName: "$[taskcat_autobucket]"
#      QSS3KeyPrefix: "quickstart-jfrog-artifactory/"
#      DatabaseInstance: "db.m5.large"
#      ArtifactoryVersion: "6.11.1"
#      NumberOfSecondary: "2"
#      ArtifactoryServerName: "artifactory"
#      CertificateDomain: "localdomain"
#      MasterKey: "override"
#      Certificate: "override"
#      CertificateKey: "override"
#      SMLicensesName: "override"
#    template: templates/jfrog-artifactory-eks-master.template.yaml
#    regions:
#      - us-west-2
#  jfrog-artifactory-eks-core:
#    parameters:
#      KubeManifestLambdaArn: "arn:aws:lambda:us-west-2:12345678911:function:tcat-tag-jfrog-artifactory-eks-KubeManifestLambda-18MK4VIN3EQ38"
#      HelmLambdaArn: "arn:aws:lambda:us-west-2:12345678911:function:tcat-tag-jfrog-artifactory-eks-30782514-HelmLambda-6QU6WP4189TC"
#      KubeConfigPath: "s3://tcat-tag-jfrog-artifactory-eks-3-kubeconfigbucket-9fm4v10gtxql/.kube/config.enc"
#      KubeGetLambdaArn: "arn:aws:lambda:us-west-2:12345678911:function:tcat-tag-jfrog-artifactory-eks-30782-KubeGetLambda-T9SC0WHIFCYY"
#      ArtifactoryS3Bucket: "tcat-tag-jfrog-artifactory-ek-artifactorys3bucket-18u65xypoqq14"
#      ArtifactoryIAMAcessKey: "AKIATXKXWAM7EYXWWYLI"
#      SecretAccessKey: "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"
#      KubeConfigKmsContext: "JFrogArtifactory"
#      ArtifactoryLicense1: "override"
#      ArtifactoryLicense2: "override"
#      ArtifactoryLicense3: "override"
#      ArtifactoryLicense4: "override"
#      ArtifactoryVersion: "6.11.1"
#      NumberOfSecondary: 1
#      ArtifactoryDBEndpointAddress: "ta1l4gu688bdgyv.cncci4pv7wym.us-west-2.rds.amazonaws.com"
#      DatabaseName: "artdb"
#      DatabaseUser: "artifactory"
#      DatabasePassword: "Admin123!"
#      MasterKey: "1ce2be4490ca2c662cb79636cf9b7b8e"
#      ArtifactoryDeploymentSize: "Small"
#      AccessCIDR: "0.0.0.0/0"
#    template: templates/jfrog-artifactory-eks-core-workload.template.yaml
#    regions:
#      - us-west-2
    

