project:
  name: quickstart-jfrog-artifactory
  owner: quickstart-eng@amazon.com
  #lambda_source_path: functions/source
  #lambda_zip_path: functions/packages
  s3_object_acl: public-read
  s3_regional_buckets: True
  s3_bucket: tcat-422383ecc658557f9a377abae675aac0  # commercial accounts
  # s3_bucket: tcat-a3e80b6745b2547da1c745b16adf2a66    # aws-seller accounts
  regions:
    - us-east-2
    #- us-gov-east-1
    #- us-gov-west-1
tests:

  # jfrog-container-registry-7102:
  #   auth:
  #     default: default
  #     us-gov-west-1: gov
  #     us-gov-east-1: gov
  #   parameters:
  #     AvailabilityZone: "$[taskcat_genaz_1]"
  #     KeyPairName: "ArtCldFrm1"
  #     ArtifactVersion: 7.10.2
  #     RemoteAccessCidr: "0.0.0.0/0"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/jfrog-ami-master.template.yaml
  #   regions:
  #     - us-east-1

  # jfrog-artifactory-7102:
  #   auth:
  #     default: default
  #     us-gov-west-1: gov
  #     us-gov-east-1: gov
  #   parameters:
  #     AvailabilityZone: "$[taskcat_genaz_1]"
  #     KeyPairName: "ArtCldFrm1"
  #     # ArtifactVersion: 7.7.3
  #     ArtifactVersion: 7.10.2
  #     RemoteAccessCidr: "0.0.0.0/0"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/jfrog-ami-master.template.yaml
  #   regions:
  #     - us-east-1

  # jfrog-xray-3103:
  #   auth:
  #     default: default
  #     us-gov-west-1: gov
  #     us-gov-east-1: gov
  #   parameters:
  #     AvailabilityZone: "$[taskcat_genaz_1]"
  #     KeyPairName: "ArtCldFrm1"
  #     # XrayVersion: 3.8.6
  #     XrayVersion: 3.10.3
  #     RemoteAccessCidr: "0.0.0.0/0"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/ami-rt-xray-master.template.yaml
  #   regions:
  #     - us-east-1


  # jfrog-artifactory-xray-ec2-postgres:
  #   auth:
  #     default: default
  #     us-gov-west-1: gov
  #     us-gov-east-1: gov
  #     us-west-2: outposts
  #   parameters:
  #     KeyPairName: "ArtCldFrm1"
  #     ArtifactoryVersion: 7.10.2
  #     RemoteAccessCidr: "0.0.0.0/0"
  #     DatabaseEngine: Postgres
  #     AccessCidr: "0.0.0.0/0"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #     DatabaseInstance: "db.m5.large"
  #     NumberOfSecondary: "2"
  #     KeystorePassword: "$[taskcat_genpass_8A]"
  #     AnsibleVaultPass: "$[taskcat_genpass_8A]"
  #     ArtifactoryServerName: "artifactory3"
  #     MasterKey: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
  #     SmLicenseCertName: "jfrog-artifactory"
  #     MultiAzDatabase: "false"
  #     # InstallXray: "false"
  #     XrayVersion: 3.10.3
  #     XrayDatabasePassword: "$[taskcat_genpass_8A]"
  #     # XrayNumberOfInstances: 2

  #   #   AvailabilityZones: "$[taskcat_genaz_2]"
  #   # template: templates/jfrog-artifactory-ec2-master.template.yaml

  #     # after creating a VPC, comment line above and uncomment lines below for faster iteration
  #     AvailabilityZones: "us-west-2a, us-west-2b"
  #     VpcId: "vpc-0fa558e8a7d82d196"
  #     PublicSubnet1Id: "subnet-094ff1213f3d4a5ac"
  #     PrivateSubnet1Id: "subnet-07c34949cc8adc081"
  #     PublicSubnet2Id: "subnet-001e856bd26ad893d"
  #     PrivateSubnet2Id: "subnet-074daa60cbe49d9c4"
  #   template: templates/jfrog-artifactory-ec2-existing-vpc.template.yaml

  #   regions:
  #     - us-east-1


  # jfrog-artifactory-simple:
  #   parameters:
  #     KeyPairName: "ArtCldFrm1"
  #     AvailabilityZones: "$[taskcat_genaz_2]"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/jfrog-artifactory-ec2-simple-master.template.yaml
  #   regions:
  #     - us-east-2
  # jfrog-artifactory-ecs-mysql:
  #   parameters:
  #     KeyPairName: "ArtCldFrm1"
  #     RemoteAccessCidr: "0.0.0.0/0"
  #     AccessCidr: "0.0.0.0/0"
  #     AvailabilityZones: "$[taskcat_genaz_2]"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #     # DatabaseInstance: "db.m5.large"
  #     # DatabaseEngine: MySQL
  #     ArtifactoryVersion: "7.10.2"
  #     # ReleaseStage: "GA"
  #     NumberOfSecondary: "2"
  #     AnsibleVaultPass: "$[taskcat_genpass_8A]"
  #     ArtifactoryServerName: "artifactory"
  #     MasterKey: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
  #     SmLicenseCertName: "jfrog-artifactory"
  #     MultiAzDatabase: "false"
  #   template: templates/jfrog-artifactory-ecs-master.template.yaml
  #   regions:
  #     - us-east-2
  #       # - us-east-2
  #       - us-west-1
  #       # - us-west-1
  #       - eu-central-1
  #       - eu-west-1
  #       - eu-west-2
  #       # - eu-west-3
  #       # - ap-southeast-2
  #       # - eu-north-1
  #       # - ca-central-1
  #       # - sa-east-1
  #       # - eu-south-1
  #       # - af-south-1
  # jfrog-artifactory-eks:
  #   auth:
  #     default: temp
  #   parameters:
  #     KeyPairName: "ArtCldFrm1"
  #     RemoteAccessCidr: "0.0.0.0/0"
  #     AccessCidr: "0.0.0.0/0"
  #     AvailabilityZones: "$[taskcat_genaz_3]"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #     DatabaseInstance: "db.m5.large"
  #     ArtifactoryVersion: "7.2.1"
  #     NumberOfSecondary: "2"
  #     ArtifactoryServerName: "artifactory"
  #     MasterKey: "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
  #     SmLicenseCertName: "jfrog-artifactory"
  #     MultiAzDatabase: "false"
  #     InstallXray: "true"
  #     XrayHelmChartVersion: 3.3.0
  #     XrayDatabasePassword: "$[taskcat_genpass_8A]"
  #     XrayNumberOfSecondary: 1
  #     RabbitMQPassword: "$[taskcat_genpass_8A]"
  #   template: templates/jfrog-artifactory-eks-master.template.yaml
  #   regions:
  #     - us-east-1
  #     # - us-east-2
  #     # - us-west-2
  # jfrog-artifactory-eks-core:
  #   parameters:
  #     ArtifactoryDeploymentSize: Medium
  #     ArtifactoryVersion: 7.2.1
  #     DatabaseEngine: Postgres
  #     DatabaseName: artdb
  #     DatabaseUser: artifactory
  #     KubeConfigKmsContext: JFrogArtifactory
  #     NumberOfSecondary: 2
  #   template: templates/jfrog-artifactory-eks-core-workload.template.yaml
