project:
  name: quickstart-jfrog-artifactory
  owner: quickstart-eng@amazon.com
  # lambda_source_path: submodules/quickstart-amazon-eks/functions/source
  # lambda_zip_path: submodules/quickstart-amazon-eks/functions/packages
  s3_object_acl: public-read
  s3_regional_buckets: True
  regions:
    - us-east-2
tests:
 #AMI will load applications and JFrog Cloud Installer Scripts
#  jfrog-rt-xray-product-ami:
#    parameters:
#      AvailabilityZone: "$[taskcat_genaz_1]"
#      KeyPairName: "$[taskcat_getkeypair]"
#      ArtifactVersion: 7.4.3
#      ArtifactRepoUrl: https://jfrog.bintray.com/artifactory-pro-rpms
#      RemoteAccessCidr: "10.0.0.0/16"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
#      QsS3BucketRegion: "$[taskcat_current_region]"
#    template: templates/ami-rt-xray-master.template.yaml
#    regions:
#      - us-east-2
#  jfrog-product-ami:
#    parameters:
#      AvailabilityZone: "$[taskcat_genaz_1]"
#      KeyPairName: "$[taskcat_getkeypair]"
#      ArtifactVersion: 7.4.3
#      ArtifactRepoUrl: https://jfrog.bintray.com/artifactory-pro-rpms
#      RemoteAccessCidr: "10.0.0.0/16"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
#      QsS3BucketRegion: "$[taskcat_current_region]"
#    template: templates/jfrog-ami-master.template.yaml
#    regions:
#      - us-east-2
 jfrog-artifactory-xray-ec2-postgres:
   parameters:
     KeyPairName: "$[taskcat_getkeypair]"
     ArtifactoryVersion: 7.5.5
     RemoteAccessCidr: "10.0.0.0/16"
     DatabaseEngine: Postgres
     AccessCidr: "10.0.0.0/16"
     AvailabilityZones: "$[taskcat_genaz_2]"
     DatabasePassword: "$[taskcat_genpass_8A]"
     QsS3BucketName: "$[taskcat_autobucket]"
     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
     QsS3BucketRegion: "$[taskcat_current_region]"
     DatabaseInstance: "db.m4.large"
     NumberOfSecondary: "2"
     KeystorePassword: "$[taskcat_genpass_8A]"
     AnsibleVaultPass: "$[taskcat_genpass_8A]"
     ArtifactoryServerName: "artifactory"
     MasterKey: "override"
     SmLicenseCertName: "override"
     MultiAzDatabase: "false"
     InstallXray: "true"
     XrayVersion: 3.3.0
     XrayDatabasePassword: "$[taskcat_genpass_8A]"
     XrayNumberOfSecondary: 1
   template: templates/jfrog-artifactory-ec2-master.template.yaml
   regions:
     - us-east-2
#  jfrog-artifactory-ecs-postgres:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      RemoteAccessCidr: "10.0.0.0/16"
#      AccessCidr: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_2]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
#      QsS3BucketRegion: "$[taskcat_current_region]"
#      DatabaseInstance: "db.m4.large"
#      DatabaseEngine: Postgres
#      ArtifactoryVersion: "7.4.3"
#      ReleaseStage: "GA"
#      NumberOfSecondary: "2"
#      AnsibleVaultPass: "$[taskcat_genpass_8A]"
#      ArtifactoryServerName: "artifactory"
#      MasterKey: "override"
#      SmLicenseCertName: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-artifactory-ecs-master.template.yaml
#    regions:
#      - us-east-2
#  jfrog-artifactory-eks:
#    parameters:
#      KeyPairName: "$[taskcat_getkeypair]"
#      RemoteAccessCidr: "10.0.0.0/16"
#      AccessCidr: "10.0.0.0/16"
#      AvailabilityZones: "$[taskcat_genaz_3]"
#      DatabasePassword: "$[taskcat_genpass_8A]"
#      QsS3BucketName: "$[taskcat_autobucket]"
#      QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
#      QsS3BucketRegion: "$[taskcat_current_region]"
#      DatabaseInstance: "db.m4.large"
#      ArtifactoryVersion: "7.4.3"
#      NumberOfSecondary: "2"
#      ArtifactoryServerName: "artifactory"
#      MasterKey: "override"
#      SmLicenseCertName: "override"
#      MultiAzDatabase: "false"
#    template: templates/jfrog-artifactory-eks-master.template.yaml
#    regions:
#      - us-east-2
#  jfrog-artifactory-eks-core:
#    parameters:
#      ArtifactoryDeploymentSize: Medium
#      ArtifactoryVersion: 7.4.3
#      DatabaseEngine: Postgres
#      DatabaseName: artdb
#      DatabaseUser: artifactory
#      KubeConfigKmsContext: JFrogArtifactory
#      NumberOfSecondary: 2
#    template: templates/jfrog-artifactory-eks-core-workload.template.yaml
