project:
  name: quickstart-jfrog-artifactory
  owner: quickstart-eng@amazon.com
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_object_acl: public-read
  s3_regional_buckets: True
  s3_bucket: tcat-422383ecc658557f9a377abae675aac0
  regions:
    - us-east-1
    #- us-gov-east-1
    #- us-gov-west-1
tests:
  # jfrog-artifactory-product-ami:
  #   auth:
  #     default: default
  #     us-gov-west-1: gov
  #     us-gov-east-1: gov
  #   parameters:
  #     AvailabilityZone: "$[taskcat_genaz_1]"
  #     KeyPairName: "ArtCldFrm1"
  #     ArtifactVersion: 7.5.5
  #     RemoteAccessCidr: "10.0.0.0/16"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/jfrog-ami-master.template.yaml
  #   regions:
  #     - us-gov-east-1
  # jfrog-xray-product-ami:
  #   auth:
  #     default: default
  #     us-gov-west-1: gov
  #     us-gov-east-1: gov
  #   parameters:
  #     AvailabilityZone: "$[taskcat_genaz_1]"
  #     KeyPairName: "ArtCldFrm1"
  #     XrayVersion: 3.8.0
  #     RemoteAccessCidr: "10.0.0.0/16"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #   template: templates/ami-rt-xray-master.template.yaml
  #   regions:
  #     - us-gov-east-1
  jfrog-artifactory-xray-ec2-postgres:
    auth:
      default: default
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:
      KeyPairName: "ArtCldFrm1"
      ArtifactoryVersion: 7.5.5
      RemoteAccessCidr: "10.0.0.0/16"
      DatabaseEngine: Postgres
      AccessCidr: "10.0.0.0/16"
      AvailabilityZones: "$[taskcat_genaz_2]"
      DatabasePassword: "$[taskcat_genpass_8A]"
      QsS3BucketName: "$[taskcat_autobucket]"
      QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
      QsS3BucketRegion: "$[taskcat_current_region]"
      DatabaseInstance: "db.m5.large"
      NumberOfSecondary: "2"
      KeystorePassword: "$[taskcat_genpass_8A]"
      AnsibleVaultPass: "$[taskcat_genpass_8A]"
      ArtifactoryServerName: "artifactory"
      MasterKey: "override"
      SmLicenseCertName: "override"
      MultiAzDatabase: "false"
    template: templates/jfrog-artifactory-ec2-master.template.yaml
    regions:
      - us-east-1
      # - us-west-2
      # - us-east-2
      # - us-west-1
      # - eu-central-1
      # - eu-west-1
      # - eu-west-2
      # - eu-west-3      
      # - ap-southeast-2
      # - eu-north-1
      # - eu-central-1
      # - sa-east-1
      # - eu-south-1
      # - af-south-1
  # jfrog-artifactory-ecs-mysql:
  #   parameters:
  #     KeyPairName: "$[taskcat_getkeypair]"
  #     RemoteAccessCidr: "10.0.0.0/16"
  #     AccessCidr: "10.0.0.0/16"
  #     AvailabilityZones: "$[taskcat_genaz_2]"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #     DatabaseInstance: "db.m5.large"
  #     DatabaseEngine: MySQL
  #     ArtifactoryVersion: "7.2.1"
  #     ReleaseStage: "GA"
  #     NumberOfSecondary: "2"
  #     AnsibleVaultPass: "$[taskcat_genpass_8A]"
  #     ArtifactoryServerName: "artifactory"
  #     MasterKey: "override"
  #     SmLicenseCertName: "override"
  #     MultiAzDatabase: "false"
  #   template: templates/jfrog-artifactory-ecs-master.template.yaml
  #   regions:
  #       - us-east-1
  #       - us-west-2
  #       - us-east-2
  #       # - us-west-1
  #       - eu-central-1
  #       - eu-west-1
  #       - eu-west-2
  #       # - eu-west-3
  #       # - ap-southeast-2
  #       # - eu-north-1
  #       # - ca-central-1
  #       # - sa-east-1
  #       # - eu-south-1
  #       # - af-south-1
  # jfrog-artifactory-eks:
  #   parameters:
  #     KeyPairName: "$[taskcat_getkeypair]"
  #     RemoteAccessCidr: "10.0.0.0/16"
  #     AccessCidr: "10.0.0.0/16"
  #     AvailabilityZones: "$[taskcat_genaz_3]"
  #     DatabasePassword: "$[taskcat_genpass_8A]"
  #     QsS3BucketName: "$[taskcat_autobucket]"
  #     QsS3KeyPrefix: "quickstart-jfrog-artifactory/"
  #     QsS3BucketRegion: "$[taskcat_current_region]"
  #     DatabaseInstance: "db.m5.large"
  #     ArtifactoryVersion: "7.2.1"
  #     NumberOfSecondary: "2"
  #     ArtifactoryServerName: "artifactory"
  #     MasterKey: "override"
  #     SmLicenseCertName: "override"
  #     MultiAzDatabase: "false"
  #   template: templates/jfrog-artifactory-eks-master.template.yaml
  #   regions:
  #     # - us-east-1
  #     - us-west-2
  #     - us-east-2
  #     - eu-west-1
  #     - eu-west-2
  #     # - eu-west-3
  #     - eu-central-1
  # jfrog-artifactory-eks-core:
  #   parameters:
  #     ArtifactoryDeploymentSize: Medium
  #     ArtifactoryVersion: 7.2.1
  #     DatabaseEngine: Postgres
  #     DatabaseName: artdb
  #     DatabaseUser: artifactory
  #     KubeConfigKmsContext: JFrogArtifactory
  #     NumberOfSecondary: 2
  #   template: templates/jfrog-artifactory-eks-core-workload.template.yaml
