---

- name: Add Artifactory Repo
  yum_repository:
    name: bintray--jfrog-artifactory-pro-rpms
    description: bintray--jfrog-artifactory-pro-rpms
    baseurl: https://jfrog.bintray.com/artifactory-pro-rpms
    gpgcheck: no
    enabled: yes

- name: Install Artifactory from RPM
  yum:
    name: jfrog-artifactory-pro
    state: installed
    releasever: "{{ artifactory_version }}"
    enablerepo: bintray--jfrog-artifactory-pro-rpms
    disablerepo: "epel,amzn-main,amzn-updates"

- name: Update Java
  package:
   name: "{{ java_version }}"
   state: present

- name: Configure Java
  alternatives:
    name: java
    path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java 

- name: Download mysql Driver
  get_url:
    url: https://bintray.com/artifact/download/bintray/jcenter/mysql/mysql-connector-java/5.1.38/mysql-connector-java-5.1.38.jar
    dest: /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.38.jar
    owner: artifactory
    group: artifactory

#- name: Configure Java
#  lineinfile:
#    path: /var/opt/jfrog/artifactory/etc/default
#    line: export JAVA_OPTIONS={{ java_options }}
#    create: yes

- name: Configure Ping
  lineinfile:
    path: /var/opt/jfrog/artifactory/etc/artifactory.system.properties
    line: artifactory.ping.allowUnauthenticated=true
    create: yes
