---

- name: Add Artifactory Repo
  yum_repository:
    name: artifactory
    description: Artifactory YUM repo
    baseurl: https://bintray.com/jfrog/artifactory-pro-rpms/rpm

- name: Install Artifactory from RPM
  yum:
    name: jfrog-artifactory-pro
    state: installed
    releasever: "{{ artifactory_version }}"

- name: Download mysql Driver
  get_url:
    url: https://bintray.com/artifact/download/bintray/jcenter/mysql/mysql-connector-java/5.1.38/mysql-connector-java-5.1.38.jar
    dest: /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.38.jar
    owner: artifactory
    group: artifactory

- name: Configure Java
  lineinfile:
    path: /var/opt/jfrog/artifactory/etc/default
    line: export JAVA_OPTIONS={{ java_options }}
    create: yes

- name: Configure Ping
  lineinfile:
    path: /var/opt/jfrog/artifactory/etc/artifactory.system.properties
    line: artifactory.ping.allowUnauthenticated=true
    create: yes