---
# defaults file for artifactory-ami

artifactory_ami_user: centos
artifactory_ami_version: 7.0.0 #6.17.0
artifactory_ami_java_version: java-1.8.0

artifactory_ami_repo_url: https://earlyaccess.jfrog.io/artifactory/enterprise-rpms # https://jfrog.bintray.com/artifactory-pro-rpms 
artifactory_ami_import_rds: true
artifactory_ami_keystore:
  path: /etc/alternatives/jre_1.8.0/lib/security/cacerts
  default_password: changeit
  new_keystore_pass: needs_to_be_passed

artifactory_ami_java_db_drivers:
  - name: mysql
    url: https://bintray.com/artifact/download/bintray/jcenter/mysql/mysql-connector-java/5.1.38/mysql-connector-java-5.1.38.jar
    dest: /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.38.jar
    owner: artifactory
    group: artifactory
  - name: postgres
    url: https://jdbc.postgresql.org/download/postgresql-42.2.9.jar
    dest: /opt/jfrog/artifactory/tomcat/lib/postgresql-42.2.9.jar
    owner: artifactory
    group: artifactory
artifactory_ami_java_db_certs:
  - name: ca-bundled
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /root/rds-combined-ca-bundle.pem
    owner: root
    group: root
    cert_alias: rds_ca
  - name: ca-root
    url: https://s3.amazonaws.com/rds-downloads/rds-ca-2019-root.pem
    dest: /root/rds-ca-2019-root.pem
    owner: root
    group: root
    cert_alias: rds_root