---
# defaults file for quickstart-jfrog-artifactory/scripts/roles/artifactory

db_type: mysql
db_driver: com.mysql.jdbc.Driver
db_ipaddr: 127.0.0.1
db_name: artifactory
db_user: artuser
db_password: badpassword

s3_endpoint: needs_to_be_passed
s3_access_key: needs_to_be_passed
s3_access_secret_key: needs_to_be_passed
s3_bucket: needs_to_be_passed

art_primary: true
java_version: java-1.8.0
java_mysql_driver:
  url: https://bintray.com/artifact/download/bintray/jcenter/mysql/mysql-connector-java/5.1.38/mysql-connector-java-5.1.38.jar
  dest: /opt/jfrog/artifactory/tomcat/lib/mysql-connector-java-5.1.38.jar
  owner: artifactory
  group: artifactory
rds_cert:
  url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
  dest: /root/rds-combined-ca-bundle.pem
  owner: root
  group: root
  cert_alias: rds_ca
artifactory_keystore_path: /etc/alternatives/jre_1.8.0/lib/security/cacerts
artifactory_keystore_default: changeit
artifactory_keystore_pass: needs_to_be_passed
  
